#pragma once

namespace	AUTOTEST
{

	//IEID_BASE
#define    IE_GSM_BASE         (5000)
#define    IE_TD_BASE          (20000)
#define    IE_TD_HSDPA_BASE    (40000)
#define    IE_TD_MBMS_BASE     (50000)
#define    IE_COMMON_BASE      (62000)
#define    IE_WCDMA_BASE       (72000)
#define    IE_CDMA_BASE        (92000)
#define    IE_WLAN_BASE        (112000)
#define	   IE_LTE_BASE		   (132000)

#define    IE_COMMON_GPSINFO_GPS_QUALITYNUM_MAX      12//最多12个星


//COMMON IE

#define    IE_COMMON_RATIND                       (IE_COMMON_BASE + 1)
#define    IE_COMMON_GPRSATT_STATE                (IE_COMMON_BASE + 2)
#define    IE_COMMON_PRODUCT_NAME                 (IE_COMMON_BASE + 3)
#define    IE_COMMON_INTERFACE_VERSION            (IE_COMMON_BASE + 4)
#define    IE_COMMON_TE_SOFT_VERSION              (IE_COMMON_BASE + 5)//internal version
#define    IE_COMMON_TE_PROTOCOL_FEATURE          (IE_COMMON_BASE + 6)//协议栈特性
#define    IE_COMMON_TE_WORKMODE                  (IE_COMMON_BASE + 7)//若设备有多种工作模式，如ue ，scanner
#define    IE_COMMON_TE_HLS_VESION                (IE_COMMON_BASE + 8)
//TIME
#define    IE_COMMON_TIME_BASE                    (IE_COMMON_BASE + 10)
#define    IE_COMMON_TIME_YEAR                    (IE_COMMON_TIME_BASE + 1)
#define    IE_COMMON_TIME_MONTH                   (IE_COMMON_TIME_BASE + 2)
#define    IE_COMMON_TIME_DAY                     (IE_COMMON_TIME_BASE + 3)
#define    IE_COMMON_TIME_HOUR                    (IE_COMMON_TIME_BASE + 4)
#define    IE_COMMON_TIME_MINUTE                  (IE_COMMON_TIME_BASE + 5)
#define    IE_COMMON_TIME_SECOND                  (IE_COMMON_TIME_BASE + 6)
#define    IE_COMMON_TIME_TIMESTAMP               (IE_COMMON_TIME_BASE + 7)
//GPS Info
#define    IE_COMMON_GPSINFO_BASE                 (IE_COMMON_TIME_BASE + 10)
#define    IE_COMMON_GPSINFO_LATITUDE             (IE_COMMON_GPSINFO_BASE + 1)
#define    IE_COMMON_GPSINFO_LONGITUDE            (IE_COMMON_GPSINFO_BASE + 2)
#define    IE_COMMON_GPSINFO_ALTITUDE             (IE_COMMON_GPSINFO_BASE + 3)
#define    IE_COMMON_GPSINFO_CAR_SPEED            (IE_COMMON_GPSINFO_BASE + 4)
#define    IE_COMMON_GPSINFO_CAR_DIR              (IE_COMMON_GPSINFO_BASE + 5)
#define    IE_COMMON_GPSINFO_GPS_VALIDSTARS_NUM   (IE_COMMON_GPSINFO_BASE + 6)
#define    IE_COMMON_GPSINFO_GPS_STATE            (IE_COMMON_GPSINFO_BASE + 7)//gps state//valid,or invalid
#define    IE_COMMON_GPSINFO_GPS_QUALITY_NUM      (IE_COMMON_GPSINFO_BASE + 8)//max num = 12,
#define    IE_COMMON_GPSINFO_GPS_QUALITY_PRN0     (IE_COMMON_GPSINFO_BASE + 10)
#define    IE_COMMON_GPSINFO_GPS_QUALITY_PRN(x)   (IE_COMMON_GPSINFO_GPS_QUALITY_PRN0 + x)//x:[0,11]
#define    IE_COMMON_GPSINFO_GPS_QUALITY_SNR0     (IE_COMMON_GPSINFO_BASE + 30)
#define    IE_COMMON_GPSINFO_GPS_QUALITY_SNR(x)   (IE_COMMON_GPSINFO_GPS_QUALITY_SNR0 + x)//x:[0,11]

//SCellInfo
#define    IE_COMMON_SCELLINFO_BASE         (IE_COMMON_GPSINFO_BASE + 100)
#define    IE_COMMON_SCELLINFO_MCC          (IE_COMMON_SCELLINFO_BASE + 1)
#define    IE_COMMON_SCELLINFO_MNC          (IE_COMMON_SCELLINFO_BASE + 2)
#define    IE_COMMON_SCELLINFO_LAC          (IE_COMMON_SCELLINFO_BASE + 3)
#define    IE_COMMON_SCELLINFO_RAC          (IE_COMMON_SCELLINFO_BASE + 4)
#define    IE_COMMON_SCELLINFO_ATT          (IE_COMMON_SCELLINFO_BASE + 6)
#define    IE_COMMON_SCELLINFO_T3212        (IE_COMMON_SCELLINFO_BASE + 7)
#define    IE_COMMON_SCELLINFO_NMO          (IE_COMMON_SCELLINFO_BASE + 8)

// PDCP PDP Para
#define    IE_COMMON_PDPPARA_BASE                       (IE_COMMON_SCELLINFO_BASE + 10)
#define    IE_COMMON_PDPPARA_NUM                        (IE_COMMON_PDPPARA_BASE + 1)
#define    IE_COMMON_PDPPARA_NSAPI0                     (IE_COMMON_PDPPARA_BASE + 10)
#define    IE_COMMON_PDPPARA_NSAPI(x)                   (IE_COMMON_PDPPARA_NSAPI0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_DELAY_CLASS0               (IE_COMMON_PDPPARA_BASE + 25)
#define    IE_COMMON_PDPPARA_DELAY_CLASS(x)             (IE_COMMON_PDPPARA_DELAY_CLASS0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_RELIABILITY_CLASS0         (IE_COMMON_PDPPARA_BASE + 40)
#define    IE_COMMON_PDPPARA_RELIABILITY_CLASS(x)       (IE_COMMON_PDPPARA_RELIABILITY_CLASS0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_PEAK_THROUGHPUT0           (IE_COMMON_PDPPARA_BASE + 55)
#define    IE_COMMON_PDPPARA_PEAK_THROUGHPUT(x)         (IE_COMMON_PDPPARA_PEAK_THROUGHPUT0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_PRECEDENCE_CLASS0          (IE_COMMON_PDPPARA_BASE + 70)
#define    IE_COMMON_PDPPARA_PRECEDENCE_CLASS(x)        (IE_COMMON_PDPPARA_PRECEDENCE_CLASS0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_RADIO_PRIO0                (IE_COMMON_PDPPARA_BASE + 85)
#define    IE_COMMON_PDPPARA_RADIO_PRIO(x)              (IE_COMMON_PDPPARA_RADIO_PRIO0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_MEAN_THROUGHPUT0           (IE_COMMON_PDPPARA_BASE + 100)
#define    IE_COMMON_PDPPARA_MEAN_THROUGHPUT(x)         (IE_COMMON_PDPPARA_MEAN_THROUGHPUT0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_IPADDRESS0                 (IE_COMMON_PDPPARA_BASE + 115)
#define    IE_COMMON_PDPPARA_IPADDRESS(x)               (IE_COMMON_PDPPARA_IPADDRESS0 + x)//x:[0,14]
#define    IE_COMMON_PDPPARA_APN0                       (IE_COMMON_PDPPARA_BASE + 130)
#define    IE_COMMON_PDPPARA_APN(x)                     (IE_COMMON_PDPPARA_IPADDRESS0 + x)//x:[0,14]

//UEID
#define    IE_COMMON_UEID_BASE         (IE_COMMON_PDPPARA_BASE + 150)

#define    IE_COMMON_UEID_IMEI         (IE_COMMON_UEID_BASE + 0)

//双卡双待时
#define    IE_COMMON_UEID_IMSI_NUM     (IE_COMMON_UEID_BASE + 1)
#define    IE_COMMON_UEID_IMSI0        (IE_COMMON_UEID_BASE + 10)
#define    IE_COMMON_UEID_IMSI(x)      (IE_COMMON_UEID_IMSI0 + x)

#define    IE_COMMON_UEID_TMSI_NUM     (IE_COMMON_UEID_BASE + 2)
#define    IE_COMMON_UEID_TMSI0        (IE_COMMON_UEID_BASE + 20)
#define    IE_COMMON_UEID_TMSI(x)      (IE_COMMON_UEID_TMSI0 + x)

#define    IE_COMMON_UEID_PTMSI_NUM    (IE_COMMON_UEID_BASE + 3)
#define    IE_COMMON_UEID_PTMSI0       (IE_COMMON_UEID_BASE + 30)
#define    IE_COMMON_UEID_PTMSI(x)     (IE_COMMON_UEID_PTMSI0 + x)

//双卡双待时或一卡双号时
#define    IE_COMMON_UEID_MSISDN_NUM   (IE_COMMON_UEID_BASE + 4)
#define    IE_COMMON_UEID_MSISDN0      (IE_COMMON_UEID_BASE + 40)
#define    IE_COMMON_UEID_MSISDN(x)    (IE_COMMON_UEID_MSISDN0 + x)

 
//NAS FSM STATE
#define    IE_COMMON_NAS_FSM_STATE_BASE                 (IE_COMMON_UEID_BASE + 50)
#define    IE_COMMON_NAS_FSM_STATE_MM_STATE             (IE_COMMON_NAS_FSM_STATE_BASE + 0)
#define    IE_COMMON_NAS_FSM_STATE_GMM_STATE            (IE_COMMON_NAS_FSM_STATE_BASE + 1)
#define    IE_COMMON_NAS_FSM_STATE_CC_TI                (IE_COMMON_NAS_FSM_STATE_BASE + 2)
#define    IE_COMMON_NAS_FSM_STATE_CC_STATE             (IE_COMMON_NAS_FSM_STATE_BASE + 3)
#define    IE_COMMOM_NAS_FSM_STATE_PDPNUM               (IE_COMMON_NAS_FSM_STATE_BASE + 4)
#define    IE_COMMON_NAS_FSM_STATE_SM_NSAPI0            (IE_COMMON_NAS_FSM_STATE_BASE + 5)
#define    IE_COMMON_NAS_FSM_STATE_SM_NSAPI(x)          (IE_COMMON_NAS_FSM_STATE_SM_NSAPI0 + x)//x:[0,14]
#define    IE_COMMON_NAS_FSM_STATE_SM_STATE0            (IE_COMMON_NAS_FSM_STATE_BASE + 20)
#define    IE_COMMON_NAS_FSM_STATE_SM_STATE(x)          (IE_COMMON_NAS_FSM_STATE_SM_STATE0 + x)//x:[0,14]
#define    IE_COMMON_NAS_FSM_STATE_GSMS_INST_ID         (IE_COMMON_NAS_FSM_STATE_BASE + 40)//1: MO， 2: MT
#define    IE_COMMON_NAS_FSM_STATE_GSMS_STATE           (IE_COMMON_NAS_FSM_STATE_BASE + 41)
 

#define    IE_COMMON_AS_FSM_STATE_BASE                  (IE_COMMON_NAS_FSM_STATE_BASE + 50)
#define    IE_COMMON_AS_FSM_STATE_RBID0                 (IE_COMMON_AS_FSM_STATE_BASE + 0)
#define    IE_COMMON_AS_FSM_STATE_RBID(x)               (IE_COMMON_AS_FSM_STATE_RBID0 + x)//x:[0,31]
#define    IE_COMMON_AS_FSM_STATE_RLCSTATE0             (IE_COMMON_AS_FSM_STATE_BASE + 40)
#define    IE_COMMON_AS_FSM_STATE_RLCSTATE(x)           (IE_COMMON_AS_FSM_STATE_RLCSTATE0 + x)//x:[0,31]

//MMTIMER
#define    IE_COMMON_MMTIMER_BASE                       (IE_COMMON_AS_FSM_STATE_BASE + 100)
#define    IE_COMMON_MMTIMER_TIMERNUM                   (IE_COMMON_MMTIMER_BASE + 1)
#define    IE_COMMON_MMTIMER_TIMERTYPE0                 (IE_COMMON_MMTIMER_BASE + 10)
#define    IE_COMMON_MMTIMER_TIMERTYPE(x)               (IE_COMMON_MMTIMER_TIMERTYPE0 + x)//x:[0,29]
#define    IE_COMMON_MMTIMER_TIMEREVENT0                (IE_COMMON_MMTIMER_BASE + 40)
#define    IE_COMMON_MMTIMER_TIMEREVENT(x)              (IE_COMMON_MMTIMER_TIMEREVENT0 + x)//x:[0,29]
#define    IE_COMMON_MMTIMER_TIMERVALUE0                (IE_COMMON_MMTIMER_BASE + 70)
#define    IE_COMMON_MMTIMER_TIMERVALUE(x)              (IE_COMMON_MMTIMER_TIMERVALUE0 + x)//x:[0,29]

//APP SERVICE PARA
#define    IE_COMMON_APPPARA_BASE                       (IE_COMMON_MMTIMER_BASE + 100)
#define    IE_COMMON_APPPARA_UPFTP_STATE                (IE_COMMON_APPPARA_BASE + 1)
#define    IE_COMMON_APPPARA_UPFTP_FILESIZE             (IE_COMMON_APPPARA_BASE + 2)
#define    IE_COMMON_APPPARA_UPFTP_TRANSSIZE            (IE_COMMON_APPPARA_BASE + 3)
#define    IE_COMMON_APPPARA_UPFTP_PERCENTOFFULLSIZE    (IE_COMMON_APPPARA_BASE + 5)
#define    IE_COMMON_APPPARA_UPFTP_MAXSPEED             (IE_COMMON_APPPARA_BASE + 6)
#define    IE_COMMON_APPPARA_UPFTP_MINSPEED             (IE_COMMON_APPPARA_BASE + 7)
#define    IE_COMMON_APPPARA_UPFTP_CURSPEED             (IE_COMMON_APPPARA_BASE + 8)
#define    IE_COMMON_APPPARA_UPFTP_AVGSPEED             (IE_COMMON_APPPARA_BASE + 9)
#define    IE_COMMON_APPPARA_UPFTP_USETIME              (IE_COMMON_APPPARA_BASE + 10)

#define    IE_COMMON_APPPARA_DWFTP_FILESIZE             (IE_COMMON_APPPARA_BASE + 11)
#define    IE_COMMON_APPPARA_DWFTP_STATE                (IE_COMMON_APPPARA_BASE + 12)
#define    IE_COMMON_APPPARA_DWFTP_TRANSSIZE            (IE_COMMON_APPPARA_BASE + 13)
#define    IE_COMMON_APPPARA_DWFTP_PERCENTOFFULLSIZE    (IE_COMMON_APPPARA_BASE + 14)
#define    IE_COMMON_APPPARA_DWFTP_MAXSPEED             (IE_COMMON_APPPARA_BASE + 15)
#define    IE_COMMON_APPPARA_DWFTP_MINSPEED             (IE_COMMON_APPPARA_BASE + 16)
#define    IE_COMMON_APPPARA_DWFTP_CURSPEED             (IE_COMMON_APPPARA_BASE + 17)
#define    IE_COMMON_APPPARA_DWFTP_AVGSPEED             (IE_COMMON_APPPARA_BASE + 18)
#define    IE_COMMON_APPPARA_DWFTP_USETIME              (IE_COMMON_APPPARA_BASE + 19)

#define    IE_COMMON_APPPARA_HTTP_STATE                 (IE_COMMON_APPPARA_BASE + 20)
#define    IE_COMMON_APPPARA_HTTP_AVGSPEED              (IE_COMMON_APPPARA_BASE + 21)
#define    IE_COMMON_APPPARA_HTTP_CURSPEED              (IE_COMMON_APPPARA_BASE + 22)
#define    IE_COMMON_APPPARA_HTTP_ELAPSETIME            (IE_COMMON_APPPARA_BASE + 23)
#define    IE_COMMON_APPPARA_HTTP_PERCENT               (IE_COMMON_APPPARA_BASE + 24)
#define    IE_COMMON_APPPARA_HTTP_COMPLETESIZE          (IE_COMMON_APPPARA_BASE + 25)
#define    IE_COMMON_APPPARA_HTTP_FILESIZE              (IE_COMMON_APPPARA_BASE + 26)
#define    IE_COMMON_APPPARA_HTTP_MAXCURSPEED           (IE_COMMON_APPPARA_BASE + 27)
#define    IE_COMMON_APPPARA_HTTP_MINCURSPEED           (IE_COMMON_APPPARA_BASE + 28)

#define    IE_COMMON_APPPARA_PING_STATE                 (IE_COMMON_APPPARA_BASE + 29)
#define    IE_COMMON_APPPARA_PING_HOST                  (IE_COMMON_APPPARA_BASE + 30)
#define    IE_COMMON_APPPARA_PING_COUNT                 (IE_COMMON_APPPARA_BASE + 31)
#define    IE_COMMON_APPPARA_PING_SIZE                  (IE_COMMON_APPPARA_BASE + 32)
#define    IE_COMMON_APPPARA_PING_SUCCTIME              (IE_COMMON_APPPARA_BASE + 33)
#define    IE_COMMON_APPPARA_PING_SUCCRATE              (IE_COMMON_APPPARA_BASE + 34)
#define    IE_COMMON_APPPARA_PING_RTTMAX                (IE_COMMON_APPPARA_BASE + 35)
#define    IE_COMMON_APPPARA_PING_RTTMIN                (IE_COMMON_APPPARA_BASE + 36)
#define    IE_COMMON_APPPARA_PING_RTTAVG                (IE_COMMON_APPPARA_BASE + 37)
#define    IE_COMMON_APPPARA_PING_OUTMSG                (IE_COMMON_APPPARA_BASE + 61)

#define    IE_COMMON_APPPARA_MMS_STATE                  (IE_COMMON_APPPARA_BASE + 38)
#define    IE_COMMON_APPPARA_MMS_SEND_TIME              (IE_COMMON_APPPARA_BASE + 39)
#define    IE_COMMON_APPPARA_MMS_PUSH_TIME              (IE_COMMON_APPPARA_BASE + 40)
#define    IE_COMMON_APPPARA_MMS_RECV_TIME              (IE_COMMON_APPPARA_BASE + 41)
#define    IE_COMMON_APPPARA_MMS_SIZE                   (IE_COMMON_APPPARA_BASE + 42)

#define    IE_COMMON_APPPARA_WAP_FRESH_STATE                (IE_COMMON_APPPARA_BASE + 43)
#define    IE_COMMON_APPPARA_WAP_FRESH_TIME                 (IE_COMMON_APPPARA_BASE + 44)
#define    IE_COMMON_APPPARA_WAP_FRESH_ICON_NUM             (IE_COMMON_APPPARA_BASE + 45)
#define    IE_COMMON_APPPARA_WAP_FRESH_DWSUCCESS_ICON_NUM   (IE_COMMON_APPPARA_BASE + 46)

#define    IE_COMMON_APPPARA_WAP_DW_STATE               (IE_COMMON_APPPARA_BASE + 47)
#define    IE_COMMON_APPPARA_WAP_DW_TIME                (IE_COMMON_APPPARA_BASE + 48)
#define    IE_COMMON_APPPARA_WAP_DW_SPEED               (IE_COMMON_APPPARA_BASE + 49)

#define    IE_COMMON_APPPARA_SMS_SEND_STATE             (IE_COMMON_APPPARA_BASE + 50)
#define    IE_COMMON_APPPARA_SMS_RECV_STATE             (IE_COMMON_APPPARA_BASE + 51)
#define    IE_COMMON_APPPARA_SMS_SEND_TIME              (IE_COMMON_APPPARA_BASE + 52)
#define    IE_COMMON_APPPARA_SMS_RECV_TIME              (IE_COMMON_APPPARA_BASE + 53)

#define    IE_COMMON_APPPARA_EMAIL_STATE                  (IE_COMMON_APPPARA_BASE + 54)
#define    IE_COMMON_APPPARA_EMAIL_SEND_TIME              (IE_COMMON_APPPARA_BASE + 55)
#define    IE_COMMON_APPPARA_EMAIL_RECV_TIME              (IE_COMMON_APPPARA_BASE + 56)

#define    IE_COMMON_APPPARA_WAP_LOGIN_STATE                (IE_COMMON_APPPARA_BASE + 57)
#define    IE_COMMON_APPPARA_WAP_LOGIN_TIME                 (IE_COMMON_APPPARA_BASE + 58)
#define    IE_COMMON_APPPARA_WAP_LOGIN_ICON_NUM             (IE_COMMON_APPPARA_BASE + 59)
#define    IE_COMMON_APPPARA_WAP_LOGIN_DWSUCCESS_ICON_NUM   (IE_COMMON_APPPARA_BASE + 60)


#define		IE_COMMON_APPPARA_MMS_SEND_STATE						(IE_COMMON_APPPARA_BASE + 62)
#define		IE_COMMON_APPPARA_MMS_PUSH_STATE						(IE_COMMON_APPPARA_BASE + 63)

//huxiufeng
#define IE_COMMON_APPPARA_WAP_MEAN_WAPHomePageTime		(IE_COMMON_APPPARA_BASE + 64)	
#define IE_COMMON_APPPARA_WAP_DownloadRate			(IE_COMMON_APPPARA_BASE + 65)

//TD-FTP-下载数据量
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_TD		(IE_COMMON_APPPARA_BASE + 66)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_R4		(IE_COMMON_APPPARA_BASE + 67)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_HSDPA		(IE_COMMON_APPPARA_BASE + 68)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_GPRS		(IE_COMMON_APPPARA_BASE + 69)

//WCDMA-FTP-数据量
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_WCDMA		(IE_COMMON_APPPARA_BASE + 70)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_WCDMA_R4		(IE_COMMON_APPPARA_BASE + 71)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_WCDMA_HSDPA		(IE_COMMON_APPPARA_BASE + 72)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_WCDMA_GPRS		(IE_COMMON_APPPARA_BASE + 73)
#define IE_COMMON_APPPARA_ULFTP_TRANSSIZE_WCDMA		(IE_COMMON_APPPARA_BASE + 74)
#define IE_COMMON_APPPARA_ULFTP_TRANSSIZE_WCDMA_R4		(IE_COMMON_APPPARA_BASE + 75)
#define IE_COMMON_APPPARA_ULFTP_TRANSSIZE_WCDMA_HSUPA		(IE_COMMON_APPPARA_BASE + 76)
#define IE_COMMON_APPPARA_ULFTP_TRANSSIZE_WCDMA_GPRS		(IE_COMMON_APPPARA_BASE + 77)


//EVDO-FTP-数据量
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_EVDO_SUM		(IE_COMMON_APPPARA_BASE + 78)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_1X_SUM		(IE_COMMON_APPPARA_BASE + 79)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_EVDO		(IE_COMMON_APPPARA_BASE + 80)
#define IE_COMMON_APPPARA_DWFTP_TRANSSIZE_1X		(IE_COMMON_APPPARA_BASE + 81)


//LAYERMSG
#define    IE_COMMON_LAYERMSG_BASE               (IE_COMMON_APPPARA_BASE + 100)
#define    IE_COMMON_LAYERMSG_RAT                (IE_COMMON_LAYERMSG_BASE + 0)
#define    IE_COMMON_LAYERMSG_MSGNUM             (IE_COMMON_LAYERMSG_BASE + 1)//max : 16
#define    IE_COMMON_LAYERMSG_MSGID0             (IE_COMMON_LAYERMSG_BASE + 2)
#define    IE_COMMON_LAYERMSG_MSGID(x)           (IE_COMMON_LAYERMSG_MSGID0 + x)//x:[0,15]
#define    IE_COMMON_LAYERMSG_MSGNAME0           (IE_COMMON_LAYERMSG_BASE + 30)
#define    IE_COMMON_LAYERMSG_MSGNAME(x)         (IE_COMMON_LAYERMSG_MSGNAME0 + x)//x:[0,15]
#define    IE_COMMON_LAYERMSG_SEGTYPE0           (IE_COMMON_LAYERMSG_BASE + 50)
#define    IE_COMMON_LAYERMSG_SEGTYPE(x)         (IE_COMMON_LAYERMSG_SEGTYPE0 + x)//x:[0,15]
#define    IE_COMMON_LAYERMSG_MSGDIR             (IE_COMMON_LAYERMSG_BASE + 71)
#define    IE_COMMON_LAYERMSG_MSGLAYER           (IE_COMMON_LAYERMSG_BASE + 72)
#define    IE_COMMON_LAYERMSG_CONTENT            (IE_COMMON_LAYERMSG_BASE + 73)
#define    IE_COMMON_LAYERMSG_DECODEENTRY        (IE_COMMON_LAYERMSG_BASE + 74)

//evnet
#define    IE_COMMON_EVENT_BASE                 (IE_COMMON_LAYERMSG_BASE + 100)
#define    IE_COMMON_EVENT_NUM                  (IE_COMMON_EVENT_BASE + 0)//max num = 20
#define    IE_COMMON_EVENT_TYPE0                (IE_COMMON_EVENT_BASE + 1)
#define    IE_COMMON_EVENT_TYPE(x)              (IE_COMMON_EVENT_TYPE0 + x)//x:[0,19]
#define    IE_COMMON_EVENT_ID0                  (IE_COMMON_EVENT_BASE + 21)
#define    IE_COMMON_EVENT_ID(x)                (IE_COMMON_EVENT_ID0 + x)


//VP IE

#define    IE_COMMON_APPPARA_VP_BASE            (IE_COMMON_EVENT_BASE + 150)
#define     IE_COMMON_APPPARA_VP_TD_MOS_I     (IE_COMMON_APPPARA_VP_BASE+1)
#define     IE_COMMON_APPPARA_VP_TD_MOS_A     (IE_COMMON_APPPARA_VP_BASE+2)
#define     IE_COMMON_APPPARA_VP_TD_MOS_V     (IE_COMMON_APPPARA_VP_BASE+3)
#define     IE_COMMON_APPPARA_VP_TD_MOS_S     (IE_COMMON_APPPARA_VP_BASE+4)
#define     IE_COMMON_APPPARA_VP_TD_RFACT     (IE_COMMON_APPPARA_VP_BASE+5)
#define     IE_COMMON_APPPARA_VP_TD_SKIPFRAME     (IE_COMMON_APPPARA_VP_BASE+6)
#define     IE_COMMON_APPPARA_VP_TD_S1     (IE_COMMON_APPPARA_VP_BASE+7)
#define     IE_COMMON_APPPARA_VP_TD_S2     (IE_COMMON_APPPARA_VP_BASE+8)
#define     IE_COMMON_APPPARA_VP_TD_S3     (IE_COMMON_APPPARA_VP_BASE+9)
#define     IE_COMMON_APPPARA_VP_TD_S4     (IE_COMMON_APPPARA_VP_BASE+10)
#define     IE_COMMON_APPPARA_VP_TD_S5     (IE_COMMON_APPPARA_VP_BASE+11)
#define     IE_COMMON_APPPARA_VP_TD_S6     (IE_COMMON_APPPARA_VP_BASE+12)
#define     IE_COMMON_APPPARA_VP_TD_S7     (IE_COMMON_APPPARA_VP_BASE+13)
#define     IE_COMMON_APPPARA_VP_TD_S8     (IE_COMMON_APPPARA_VP_BASE+14)
#define     IE_COMMON_APPPARA_VP_TD_S9     (IE_COMMON_APPPARA_VP_BASE+15)
#define     IE_COMMON_APPPARA_VP_TD_S10     (IE_COMMON_APPPARA_VP_BASE+16)

#define    IE_COMMON_APPPARA_MOSSCORE0          (IE_COMMON_EVENT_BASE + 200)
//#define    IE_COMMON_APPPARA_MOSSCORE(x)        (IE_COMMON_APPPARA_MOSSCORE0 + x)
#define    IE_COMMON_APPPARA_MOSSCOREUSETIME0   (IE_COMMON_EVENT_BASE + 210)
//#define    IE_COMMON_APPPARA_MOSSCOREUSETIME(x) (IE_COMMON_APPPARA_MOSSCOREUSETIME0 + x)
}

#define TD_SEAHIGH_SCAN_PCCPCH_BASE			    	(IE_COMMON_EVENT_BASE + 500)	//x:0-31
#define TD_SEAHIGH_SCAN_CODENUM                     (TD_SEAHIGH_SCAN_PCCPCH_BASE + 0)
#define TD_SEAHIGH_SCAN_PCCPCH_FREQ0                (TD_SEAHIGH_SCAN_PCCPCH_BASE + 10)
#define TD_SEAHIGH_SCAN_PCCPCH_FREQ(x)				(TD_SEAHIGH_SCAN_PCCPCH_FREQ0 + x)
#define TD_SEAHIGH_SCAN_PCCPCH_CPI0 				(TD_SEAHIGH_SCAN_PCCPCH_BASE + 42)
#define TD_SEAHIGH_SCAN_PCCPCH_CPI(x)				(TD_SEAHIGH_SCAN_PCCPCH_CPI0 + x)
#define TD_SEAHIGH_SCAN_PCCPCH_CIR0				    (TD_SEAHIGH_SCAN_PCCPCH_BASE + 74)
#define TD_SEAHIGH_SCAN_PCCPCH_CIR(x)				(TD_SEAHIGH_SCAN_PCCPCH_CIR0 + x)
#define TD_SEAHIGH_SCAN_PCCPCH_RSCP0    			(TD_SEAHIGH_SCAN_PCCPCH_BASE + 106)
#define TD_SEAHIGH_SCAN_PCCPCH_RSCP(x)		    	(TD_SEAHIGH_SCAN_PCCPCH_RSCP0 + x)

